version: '2.28.1'
services:
  app:
    image: ansike/pystudy
    volumes:
      - app-data:/app/
    # command: /bin/bash /app/start.sh
    # command: sleep 3600
    # scp /app/nginx.conf nginx:/etc/nginx/nginx.conf
    command: 
      - /bin/sh
      - -c
      - |
        sh ./start.sh
        sleep 3600
    environment:
      - PORT=8000
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=pystudy
      - MYSQL_PASSWORD=pystudy@2024!
      - MYSQL_NAME=pystudy
      - DEBUG=false
    networks:
      - mynetwork
    ports:
      - 8001:8001
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - 9001:8000
    volumes:
      - app-data/nginx.conf:/etc/nginx/
      - app-data/static:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - app
  db:
    image: mysql:8
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql8123asd
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    
networks:
  mynetwork:
    driver: bridge
volumes:
  app-data:
