volumes:
  db-data: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db

networks:
  mynetwork:
    driver: bridge

services:
  app:
    image: pystudy/app:1.0.1
    build: 
      context: ./app
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.1
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - /app
    command: uwsgi --ini uwsgi.ini
    environment:
      - PORT=8000
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=pystudy
      - MYSQL_PASSWORD=pystudy@2024!
      - MYSQL_NAME=pystudy
      - DEBUG=false

      # 设置 superuser
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DJANGO_SUPERUSER_EMAIL=admin@pystudy.com
    networks:
      - mynetwork
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 9001:80
    volumes_from:
      - app
    networks:
      - mynetwork
    depends_on:
      - app
  db:
    image: mysql:8
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql8123asd
    networks:
      - mynetwork
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
